import { density } from './density.ts';
import { focusRing } from './focusRing.ts';
import { motion } from './motion.ts';
import { radius } from './radius.ts';
import { scrollbar } from './scrollbar.ts';
import { shadows } from './shadows.ts';
import { spacing } from './spacing.ts';
import { type ThemeName, themes, type ThemeTokens } from './themes.ts';
import { typography } from './typography.ts';
import { zIndex } from './zIndex.ts';

type Primitive = string | number;

interface TokenTree {
  readonly [key: string]: Primitive | TokenTree;
}

function toKebab(input: string): string {
  return input
    .replaceAll('.', '-')
    .replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
}

function primitiveToCss(value: Primitive): string {
  return typeof value === 'number' ? String(value) : value;
}

function entriesFromTree(prefix: string, tree: TokenTree): string[] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const name = `${prefix}-${toKebab(key)}`;
    if (typeof value === 'object') return entriesFromTree(name, value);
    return [`--${name}: ${primitiveToCss(value)};`];
  });
}

function pxTree(tree: TokenTree): TokenTree {
  return Object.fromEntries(
    Object.entries(tree).map(([key, value]) => [
      key,
      typeof value === 'object' ? pxTree(value) : `${value}px`,
    ]),
  );
}

function block(selector: string, declarations: readonly string[]): string {
  return `${selector} {\n${declarations.map((line) => `  ${line}`).join('\n')}\n}`;
}

function themeDeclarations(theme: ThemeTokens): string[] {
  return entriesFromTree('color', theme.color);
}

function sharedDeclarations(): string[] {
  return [
    ...entriesFromTree('space', spacing),
    ...entriesFromTree('radius', radius),
    ...entriesFromTree('shadow', shadows),
    ...entriesFromTree('font-family', typography.fontFamily),
    ...entriesFromTree('font-size', typography.size),
    ...entriesFromTree('font-weight', typography.weight),
    ...entriesFromTree('density', pxTree(density)),
    ...entriesFromTree('motion', motion),
    ...entriesFromTree('z', zIndex),
    `--focus-ring-width: ${focusRing.width};`,
    `--focus-ring-offset: ${focusRing.offset};`,
    `--focus-ring-color: ${focusRing.color};`,
    `--focus-ring-shadow: ${focusRing.shadow};`,
    `--scrollbar-thumb: ${scrollbar.thumb};`,
    `--scrollbar-thumb-hover: ${scrollbar.thumbHover};`,
    `--scrollbar-track: ${scrollbar.track};`,
    `--scrollbar-size: ${scrollbar.size};`,
  ];
}

export function generateThemesCss(): string {
  const themeBlocks = (Object.entries(themes) as Array<[ThemeName, ThemeTokens]>).map(
    ([name, theme]) => {
      const selector = name === 'light'
        ? ':root,\n:root[data-theme="light"]'
        : `:root[data-theme="${name}"]`;
      return block(selector, themeDeclarations(theme));
    },
  );

  return [
    '/* Generated by @firebase-desk/design-tokens. */',
    ...themeBlocks,
    block(':root', sharedDeclarations()),
    '@media (prefers-reduced-motion: reduce) {\n  :root {\n    --motion-duration-fast: 0ms;\n    --motion-duration-base: 0ms;\n    --motion-duration-slow: 0ms;\n  }\n}',
    '',
  ].join('\n\n');
}
